apiVersion: v1
kind: Service
metadata: 
  labels: 
    app: "mongodb"
  name: "mongodb-internal"
spec: 
  clusterIP: None
  ports: 
    - name: mongodb
      port: 27017
  selector: 
    app: mongodb
