apiVersion: v1
kind: PersistentVolume
metadata:
  name: mongodb-storage-0
  labels:
    type: local
    app: mongodb
spec:
  storageClassName: local-storage
  capacity:
    storage: 100Mi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/opt/pv0"
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: mongodb-storage-1
  labels:
    type: local
    app: mongodb
spec:
  storageClassName: local-storage
  capacity:
    storage: 100Mi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/opt/pv1"
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: mongodb-storage-2
  labels:
    type: local
    app: mongodb
spec:
  storageClassName: local-storage
  capacity:
    storage: 100Mi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/opt/pv2"
---
