apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mongodb
spec:
  serviceName: "mongodb-internal"
  replicas: 3
  selector:
    matchLabels:
      app: mongodb
  template:
    metadata:
      labels:
        app: mongodb
    spec:
      containers:
      - name: mongodb
        image: "registry.access.redhat.com/rhscl/mongodb-34-rhel7:latest"
        ports:
          - containerPort: 27017
        command: ["run-mongod-replication"]
        readinessProbe:
          exec:
            command:
              - stat
              - /tmp/initialized 
          initialDelaySeconds: 10
          periodSeconds: 10 
        env:
                - name: MONGODB_DATABASE
                  value: "mongodb"
                - name: MONGODB_USER
                  value: "mongodb_user"
                - name: MONGODB_PASSWORD
                  value: "mongodb_password"
                - name: MONGODB_ADMIN_PASSWORD
                  value: "mongodb_admin_password"
                - name: MONGODB_REPLICA_NAME
                  value: "rs0"
                - name: MONGODB_KEYFILE_VALUE
                  value: "12345678901234567890"
                - name: MONGODB_SERVICE_NAME
                  value: "mongodb-internal"
        volumeMounts:
        - name: mongodb-storage
          mountPath: "/var/lib/mongodb/data"
  volumeClaimTemplates:
  - metadata:
      name: mongodb-storage
    spec:
      storageClassName: local-storage
      accessModes:
        - ReadWriteOnce
      resources:
        requests:
          storage: 100Mi
